Repository MrDaseMan/fukuro-storage, pull requests merged in 2024-04, with the labels that each got.

#173 Добавление одежды на персонажей из Doki Doki Literature Club
  public/configs/characters.json
  public/graphics/sprites/mods/DDLC/mon/mk_1bl_1.png
  public/graphics/sprites/mods/DDLC/mon/mk_1bl_2.png
  public/graphics/sprites/mods/DDLC/mon/mk_1bl_3.png
  public/graphics/sprites/mods/DDLC/mon/mk_1bl_4.png
  public/graphics/sprites/mods/DDLC/mon/mk_1gdr_1.png
  public/graphics/sprites/mods/DDLC/mon/mk_1gdr_2.png
  public/graphics/sprites/mods/DDLC/mon/mk_1gdr_3.png
  public/graphics/sprites/mods/DDLC/mon/mk_1gdr_4.png
  public/graphics/sprites/mods/DDLC/mon/mk_2gdr.png
  public/graphics/sprites/mods/DDLC/say/sy_1bl_1.png
  public/graphics/sprites/mods/DDLC/say/sy_1bl_2.png
  public/graphics/sprites/mods/DDLC/say/sy_1bl_3.png
  public/graphics/sprites/mods/DDLC/say/sy_1bl_4.png
  public/graphics/sprites/mods/DDLC/say/sy_1h_1.png
  public/graphics/sprites/mods/DDLC/say/sy_1h_2.png
  public/graphics/sprites/mods/DDLC/say/sy_1h_3.png
  public/graphics/sprites/mods/DDLC/say/sy_1h_4.png
  public/graphics/sprites/mods/DDLC/say/sy_1wdr_1.png
  public/graphics/sprites/mods/DDLC/say/sy_1wdr_2.png
  public/graphics/sprites/mods/DDLC/say/sy_1wdr_3.png
  public/graphics/sprites/mods/DDLC/say/sy_1wdr_4.png
  public/graphics/sprites/mods/DDLC/say/sy_2wdr.png
  public/graphics/sprites/mods/DDLC/yur/yr_1b.png
  public/graphics/sprites/mods/DDLC/yur/yr_1bl.png
  public/graphics/sprites/mods/DDLC/yur/yr_1c.png
  public/graphics/sprites/mods/DDLC/yur/yr_1pj.png
  public/graphics/sprites/mods/DDLC/yur/yr_2b.png
  public/graphics/sprites/mods/DDLC/yur/yr_2bl.png
  public/graphics/sprites/mods/DDLC/yur/yr_2c.png
  public/graphics/sprites/mods/DDLC/yur/yr_2pj.png
  public/graphics/sprites/mods/DDLC/yur/yr_3bl.png
  public/graphics/sprites/mods/DDLC/yur/yr_3c.png
  public/graphics/sprites/mods/DDLC/yur/yr_3pj.png
  public/graphics/sprites/mods/DDLC/yur/yr_4b.png
  public/graphics/sprites/mods/DDLC/yur/yr_4bl.png
  public/graphics/sprites/mods/DDLC/yur/yr_4c.png
  public/graphics/sprites/mods/DDLC/yur/yr_4pj.png
  public/graphics/sprites/mods/Hiro/hiro_emo/hiro_pose_hoodie1.png
  public/graphics/sprites/mods/Hiro/hiro_emo/hiro_pose_hoodie2.png
Labels: Нововведение, Отложено

#174 Рефактор взрослого Артёма
  public/configs/characters.json
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_body.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_business.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_casual.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_grin.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_normal.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_normal_casual.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_serious.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_serious_casual.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_smile.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_smile2_casual.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_adl_smile_casual.png
  public/graphics/sprites/mods/Dublicate/d_ar/d_ar_parad.png
Labels: Вопрос, Нововведение, Необходимы правки

#172 Дед и чубрик
  public/configs/characters.json
  public/graphics/sprites/mods/Alternativa/de/de_1_angry.png
  public/graphics/sprites/mods/Alternativa/de/de_1_body.png
  public/graphics/sprites/mods/Alternativa/de/de_1_smile.png
  public/graphics/sprites/mods/Alternativa/ke/ke_1_angry.png
  public/graphics/sprites/mods/Alternativa/ke/ke_1_body.png
  public/graphics/sprites/mods/Alternativa/ke/ke_1_smile.png
Labels: Нужна помощь, Вопрос, Нововведение, Отложено

#175 Быстро хотфиксим мои незнания по эмоциям и исправляем пути
  configs/characters.json
  graphics/sprites/mods/I_am_Sam/sam/swimm/samb_laught.png
  graphics/sprites/mods/I_am_Sam/sam/swimm/samb_shy.png
Labels: Исправление ошибок
